### ISSUE TITLE
link to http://www.mozart-oz.org no longer works

### ISSUE THREAD

**Issue by PerBothner** [mozart/mozart#174]

**Comment by sjmackenzie** [comment]
Yeah it's sad, we lost it to domain parasites. Hopefully we can get it
back. This issue can be closed.

**Comment by PerBothner** [comment]
Ok - I just wanted to confirm that someone was aware of and working on the problem.
Is there some other temporary link to the website - even with just a numeric IP address?

**Comment by petervanroy** [comment]
On 22/3/2016 17:08, Per Bothner wrote:
>
> Ok - I just wanted to confirm that someone was aware of and working on 
> the problem.
> Is there some other temporary link to the website - even with just a 
> numeric IP address?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/mozart/mozart/issues/174#issuecomment-199883710>
>
The new link is www.mozart2.org.

Peter
