### ISSUE TITLE
Thread.suspend produces runtime errors

### ISSUE THREAD

**Issue by vishweshjatala** [mozart/mozart#200]
I am trying to use the construct Thread.suspend in my program as:

{Thread.suspend Thread.this}

It produces the following runtime error. Kindly look into the issue.

%***************** Error: illegal field selection ***************
%**
%** In statement:    R . suspend = _<optimized>
%** Expected fields: getPriority getThisPriority injectException is preempt setPriority setThisPriority state terminate this
%** Record value:    'thread'(getPriority:<P/2 Thread.getPriority> getThisPriority:<P/1 GetThisPriority> injectException:<P/2 Thread.injectException> is:<P/2 Thread.is> preempt:<P/1 Thread.preempt> setPriority:<P/2 Thread.setPriority> setThisPriority:<P/1 SetThisPriority> state:<P/2 Thread.state> terminate:<P/1 Thread.terminate> this:<P/1 Thread.this>)
%**
%** Call Stack:
%** toplevel abstraction in line 1, column 0, PC = 50460005

**Comment by layus** [comment]
The error means that the value `Thread` does not contain an entry `suspend`. You can only pick among 

getPriority getThisPriority injectException is preempt setPriority setThisPriority state terminate this

The spec at http://mozart2.org/mozart-v1/doc-1.4.0/base/thread.html has it tough, so I guess it is missing in the implem.

**Comment by layus** [comment]
Also, I guess you are using mozart2, so the right place to discuss this is at https://github.com/mozart/mozart2/pull/332 :-)
